### ISSUE TITLE
Weekend filter

### ISSUE THREAD

**Issue by roertbb** [akai-org/hackathons#6]
Display information whether hackathon is going to take place during weekend

**Comment by rrudol** [comment]
![image](https://user-images.githubusercontent.com/9325182/76122193-cda52580-5ff5-11ea-9a7f-03c52ae7d54e.png)
Probably it deserves better styling 😄 
What do you think? PR https://github.com/akai-org/hackathons/pull/11

**Comment by roertbb** [comment]
resolved in #11
